// react-travelholic/src/components/Registration/Registration.js
import React, { Component } from "react";
import axios from 'axios';
import { Link } from 'react-router-dom';

// reactstrap components
import {
    Button,
    Card,
    CardBody,
    CardFooter,
    Form,
    Input,
    InputGroup,
    Container,
    Col,
} from "reactstrap";
import DatePicker from 'react-datetime';
import format from "date-fns/format";
import InputFiles from 'react-input-files';


function Registration(props) {
    var [firstName, setFirstName] = React.useState("");
    var [lastName, setLastName] = React.useState("");
    var [username, setUsername] = React.useState("");
    var [password, setPassword] = React.useState("");
    var [caption, setCaption] = React.useState("");
    var [address, setAddress] = React.useState("");
    var [email, setEmail] = React.useState("");
    var [image, setImage] = React.useState("");
    var [birthday, setBirthday] = React.useState("");
    const [lastFocus, setLastFocus] = React.useState(false);
    var [validUsername, setValidUsername] = React.useState(true);


    React.useEffect(() => {
        document.body.classList.add("login-page");
        document.body.classList.add("sidebar-collapse");
        document.documentElement.classList.remove("nav-open");
        window.scrollTo(0, 0);
        document.body.scrollTop = 0;
        return function cleanup() {
            document.body.classList.remove("login-page");
            document.body.classList.remove("sidebar-collapse");
        };
    });

    function createAccount() {
        axios.get('/user/try/' + username).then(response => {
            if (response.data === true) {
                axios.post('/user/save', {
                    firstName: firstName,
                    lastName: lastName,
                    username: username,
                    password: password,
                    caption: caption,
                    address: address,
                    email: email,
                    birthDate: birthday,
                    newUsername: null
                }).then(response => {
                    sessionStorage.setItem('username', username);
                    if (image != "") {
                        axios.post('/user/uploadImage/' + username,  image ).then(response =>
                            console.log(response));
                            props.history.push('/home');
                    } else {
                        props.history.push('/home');
                    }

                })
            } else {
                setValidUsername(false);
            }
        })

    }

    function birthdayChange(event) {
        setBirthday( format(event._d, "yyyy-MM-dd"))
    }

    function uploadImage(imagefile){
        let data = new FormData();
        data.append('file', imagefile);
        setImage(data)    
    }



    return (
        <div className="page-header clear-filter" filter-color="blue">
            <div
                className="page-header-image"
                style={{
                    backgroundImage: "url(" + require("assets/img/login.jpg") + ")"
                }}
            ></div>
            <div className="content">
                <Container>
                    <Col className="ml-auto mr-auto" md="4">
                        <Card className="card-login card-plain">
                            <Form action="" className="form" method="">

                                <CardBody>

                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "") }>
                                        <Input
                                            placeholder="First Name..."
                                            type="text"
                                            onFocus={() => setLastFocus(true)}
                                            onBlur={() => setLastFocus(false)}
                                            onChange={(event) => setFirstName(event.target.value)}
                                        ></Input>
                                    </InputGroup>

                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "")
                                        }
                                    >

                                        <Input
                                            placeholder="Last Name..."
                                            type="text"
                                            onFocus={() => setLastFocus(true)}
                                            onBlur={() => setLastFocus(false)}
                                            onChange={(event) => setLastName(event.target.value)}
                                        ></Input>
                                    </InputGroup>

                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "")
                                        }
                                    >

                                        <Input
                                            placeholder="Username..."
                                            type="text"
                                            onFocus={() => setLastFocus(true)}
                                            onBlur={() => setLastFocus(false)}
                                            onChange={(event) => setUsername(event.target.value)}
                                        ></Input>
                                    </InputGroup>
                                    {validUsername === true ?
                                        null
                                        : <h6> Username must be unique! </h6>}
                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "")
                                        }
                                    >

                                        <Input
                                            placeholder="Password..."
                                            type="password"
                                            onFocus={() => setLastFocus(true)}
                                            onBlur={() => setLastFocus(false)}
                                            onChange={(event) => setPassword(event.target.value)}
                                        ></Input>
                                    </InputGroup>

                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "")
                                        }
                                    >

                                        <Input
                                            placeholder="Email..."
                                            type="text"
                                            onFocus={() => setLastFocus(true)}
                                            onBlur={() => setLastFocus(false)}
                                            onChange={(event) => setEmail(event.target.value)}
                                        ></Input>
                                    </InputGroup>

                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "")
                                        }
                                    >

                                        <Input
                                            placeholder="Address..."
                                            type="text"
                                            onFocus={() => setLastFocus(true)}
                                            onBlur={() => setLastFocus(false)}
                                            onChange={(event) => setAddress(event.target.value)}
                                        ></Input>
                                    </InputGroup>

                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "")
                                        }
                                    >

                                        <Input
                                            placeholder="Caption..."
                                            type="textarea"
                                            onFocus={() => setLastFocus(true)}
                                            onBlur={() => setLastFocus(false)}
                                            onChange={(event) => setCaption(event.target.value)}
                                        ></Input>
                                    </InputGroup>

                                    <InputGroup
                                        className={
                                            "no-border input-lg" +
                                            (lastFocus ? " input-group-focus" : "")
                                        }
                                    >
                                        <DatePicker
                                            placeholder="Birthday"
                                            onChange={(event) => birthdayChange(event)}
                                        />
                                    </InputGroup>

                                    <InputFiles onChange={files => uploadImage(files[0])}>
                                        <Button className="btn-round" color="info"> Upload Photo </Button>
                                    </InputFiles>

                                </CardBody>
                                <CardFooter className="text-center">
                                    <Button
                                        block
                                        className="btn-round"
                                        color="info"
                                        onClick={createAccount}
                                        size="lg">
                                        Create Account
                                    </Button>

                                    <div className="pull-left">
                                        <h6>
                                            Already have an account?
                                            <Link
                                                className="btn-round"
                                                color="info"
                                                size="lg"
                                                to="/"
                                            >
                                                Login
                                                 </Link>

                                        </h6>
                                    </div>
                                  
                                </CardFooter>
                            </Form>
                        </Card>
                    </Col>
                </Container>
            </div>
        </div>

    );
}

export default Registration;

// cilent-travelholic/src/app/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { UserDto } from '../model/user-dto';
import { UserService } from '../services/user-service';
import { HttpErrorResponse, HttpEventType } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
    selector: 'app-registration',
    templateUrl: './registration.component.html',
    styleUrls: ['./registration.component.scss']
})
export class RegistrationComponent implements OnInit {

    userDto: UserDto;
    dateBirth: String;
    uniqueUsername: boolean;
    selectedImage: File = null;
    selectedImageFD: FormData = new FormData();
    image: any

    constructor(private userService: UserService,
        private router: Router) {
        this.uniqueUsername = true;
    }

    ngOnInit() {
    }

    registrationForm = new FormGroup({
        email: new FormControl(),
        firstName: new FormControl(),
        lastName: new FormControl(),
        birthDate: new FormControl(),
        address: new FormControl(),
        username: new FormControl(),
        password: new FormControl(),
        caption: new FormControl(),
    })

    onFileChange(event) {
        this.selectedImage = event.target.files[0];
        this.selectedImageFD.append("file", this.selectedImage);
    }

    saveUser() {
        this.userDto = new UserDto();
        this.userDto.firstName = this.registrationForm.get("firstName").value;
        this.userDto.lastName = this.registrationForm.get("lastName").value;
        this.userDto.password = this.registrationForm.get("password").value;
        this.userDto.address = this.registrationForm.get("address").value;
        this.userDto.caption = this.registrationForm.get("caption").value;
        this.userDto.email = this.registrationForm.get("email").value;
        this.userDto.username = this.registrationForm.get("username").value;
        
        let dateBirth = this.registrationForm.get("birthDate").value.year + "-" + this.registrationForm.get("birthDate").value.month + "-" + this.registrationForm.get("birthDate").value.day;
        this.userDto.birthDate = dateBirth;

        this.userService.saveUser(this.userDto).subscribe(data => {
            if (this.selectedImageFD != null) {
                this.userService.pushFileToStorage(this.selectedImageFD, this.userDto.username).subscribe(data => {
                    console.log(data)
                })
            };
            sessionStorage.setItem('username', this.registrationForm.get("username").value)
            this.router.navigate(["home"]);
        }, (err: HttpErrorResponse) => {
        });
    }

    testUsername() {
        let usernameTemp = this.registrationForm.get('username').value
        this.userService.tryUsername(usernameTemp).subscribe(data => {
            if (data == true) {
                this.uniqueUsername = true
                this.saveUser()
            } else {
                this.uniqueUsername = false
                this.registrationForm.get('username').setValue('')
            }
        })
    }






}

<div class="page-header" filter-color="orange">
    <div class="page-header-image" style="background-image:url(assets/img/login.jpg)"></div>
    <div class="col-md-4 content-center">

        <div class="card card-login card-plain">
            <form [formGroup]="registrationForm">
                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input type="text" class="form-control" id="inputfirstName" placeholder="First Name"
                        formControlName="firstName" />
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input type="text" class="form-control" id="inputLastName" placeholder="Last Name"
                        formControlName="lastName">
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input type="text" class="form-control" id="inputEmail4" placeholder="Email"
                        formControlName="email">
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input class="form-control datetimepicker" placeholder="Birthday" name="dp" ngbDatepicker
                        #d="ngbDatepicker" (click)="d.toggle()" formControlName="birthDate">
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input type="text" class="form-control" id="inputUsername" placeholder="Username"
                        formControlName="username">
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input type="password" class="form-control" id="inputPassword4" placeholder="Password"
                        formControlName="password">
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input type="text" class="form-control" id="inputAddress" placeholder="Address"
                        formControlName="address">
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <textarea class="form-control" aria-label="With textarea" formControlName="caption"
                        placeholder="Caption"></textarea>
                </div>

                <div class="input-group form-group-no-border input-lg" [ngClass]="{'input-group-focus':focus===true}">
                    <input style="display: none" type="file" (change)="onFileChange($event)" #fileInput>
                    <button type="submit" class="btn btn-primary btn-round" (click)="fileInput.click()">
                        Pick
                        image</button>
                </div>


                <br>
                <span *ngIf="uniqueUsername == false" class="badge badge-danger">Username must be unique </span>
                <br>

                <button 
                    type="submit" 
                    class="btn btn-primary btn-round btn-lg" 
                    (click)="testUsername()">
                    Create account
                </button>
                <br>
                Already have an account?
                <button type="submit" class="btn btn-primary btn-round btn-lg" [routerLink]="['']"
                    routerLinkActive="router-link-active">Login</button>


            </form>

        </div>
    </div>
</div>
